import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Octokit} from "octokit";
import {useEffect} from "react";

// export async function getServerSideProps() {
//
// }

export default  function Home() {
    // return (
    //   <div className={styles.container}>
    //     <Head>
    //       <title>Create Next App</title>
    //       <meta name="description" content="Generated by create next app" />
    //       <link rel="icon" href="/favicon.ico" />
    //     </Head>
    //
    //     <main className={styles.main}>
    //       <h1 className={styles.title}>
    //         Welcome to <a href="https://nextjs.org">Next.js!</a>
    //       </h1>
    //
    //       <p className={styles.description}>
    //         Get started by editing{' '}
    //         <code className={styles.code}>pages/index.tsx</code>
    //       </p>
    //
    //       <div className={styles.grid}>
    //         <a href="https://nextjs.org/docs" className={styles.card}>
    //           <h2>Documentation &rarr;</h2>
    //           <p>Find in-depth information about Next.js features and API.</p>
    //         </a>
    //
    //         <a href="https://nextjs.org/learn" className={styles.card}>
    //           <h2>Learn &rarr;</h2>
    //           <p>Learn about Next.js in an interactive course with quizzes!</p>
    //         </a>
    //
    //         <a
    //           href="https://github.com/vercel/next.js/tree/canary/examples"
    //           className={styles.card}
    //         >
    //           <h2>Examples &rarr;</h2>
    //           <p>Discover and deploy boilerplate example Next.js projects.</p>
    //         </a>
    //
    //         <a
    //           href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //           target="_blank"
    //           rel="noopener noreferrer"
    //           className={styles.card}
    //         >
    //           <h2>Deploy &rarr;</h2>
    //           <p>
    //             Instantly deploy your Next.js site to a public URL with Vercel.
    //           </p>
    //         </a>
    //       </div>
    //     </main>
    //
    //     <footer className={styles.footer}>
    //       <a
    //         href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         Powered by{' '}
    //         <span className={styles.logo}>
    //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //         </span>
    //       </a>
    //     </footer>
    //   </div>
    //

    useEffect(()=>{
        const octokit = new Octokit({
            auth: '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'
        });
        const fetchAsyncCommitsFromGithub = async () => {
            const commitsFromGithub = await octokit.request('GET /repos/{owner}/{repo}/commits', {
                owner: 'jairovanegas',
                repo: 'git-watcher'
            });
            console.log(commitsFromGithub);
        };
        fetchAsyncCommitsFromGithub();
    });
    return (
        <div className={styles.container}>
            <Head>
                <title>GitWatcher</title>
                <meta name="description" content="Watcher of commits in it's repository"/>
                <link rel="icon" href="/gitico.png"/>
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to this <a href="https://github.com/jairovanegas/git-watcher">repository</a>
                </h1>

                <p className={styles.description}>
                    Commit History
                </p>

                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>Learn about Next.js in an interactive course with quizzes!</p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/canary/examples"
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>Discover and deploy boilerplate example Next.js projects.</p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer"
                        className={styles.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>
                            Instantly deploy your Next.js site to a public URL with Vercel.
                        </p>
                    </a>
                </div>
            </main>
        </div>
    );
}
